server:
  port: 8201

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pme_members
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
#    
#logging:
#  level:
#    '[org.springframework]': debug  
#  main:
#    allow-circular-references: true